# Generated by Django 3.2.6 on 2021-12-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rssReader', '0003_auto_20211218_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adscode',
            old_name='top_banner',
            new_name='home_ad_side',
        ),
        migrations.RenameField(
            model_name='adscode',
            old_name='bill_board',
            new_name='hor_ad_one',
        ),
        migrations.RenameField(
            model_name='adscode',
            old_name='megaBillboard',
            new_name='hor_ad_two',
        ),
        migrations.RemoveField(
            model_name='adscode',
            name='biznisSideAD',
        ),
        migrations.RemoveField(
            model_name='adscode',
            name='category_one',
        ),
        migrations.RemoveField(
            model_name='adscode',
            name='category_sideAD',
        ),
        migrations.RemoveField(
            model_name='adscode',
            name='category_two',
        ),
        migrations.RemoveField(
            model_name='adscode',
            name='sidebarAD',
        ),
        migrations.RemoveField(
            model_name='adscode',
            name='source_sideAD',
        ),
        migrations.RemoveField(
            model_name='adscode',
            name='sportSideBar',
        ),
        migrations.RemoveField(
            model_name='adscode',
            name='techSideAD',
        ),
        migrations.RemoveField(
            model_name='adscode',
            name='topSideAD',
        ),
        migrations.RemoveField(
            model_name='adscode',
            name='vijestiSideBar',
        ),
    ]
